jobs:
- job: sitl
  displayName: 'Cygwin SITL build'
  pool:
    vmImage: 'win1803'
  condition: ne(variables['Build.Reason'], 'Schedule')
  steps:
  - script: choco install --forceX86 cygwin --params "/InstallDir:C:\Cygwin /NoStartMenu /NoAdmin"
    displayName: 'Install Cygwin'
  - script: choco install --forceX86 gcc-g++ python2 python2-future python2-lxml git gettext --source cygwin
    displayName: 'Install Cygwin packages'
  - script: C:\Cygwin\bin\bash --login -c "cd $(cygpath '%BUILD_SOURCESDIRECTORY%') && ./waf --board sitl configure bin"
    displayName: 'Build SITL'
  - script: C:\Cygwin\bin\bash --login -c "cd $(cygpath '%BUILD_SOURCESDIRECTORY%') && cygcheck.exe build/sitl/bin/*"
    displayName: 'Check dependencies'
  - script: C:\Cygwin\bin\bash --login -c "cd $(cygpath '%BUILD_SOURCESDIRECTORY%') && cp $(cygcheck.exe build/sitl/bin/* | grep Cygwin | grep -v '.exe' | sed 's/^[ \t]*//' | sort | uniq) build/sitl/bin/"
    displayName: 'Copy dependencies to build dir'
  - task: PublishBuildArtifacts@1
#  - task: PublishPipelineArtifact@0
    displayName: 'Publish build artifacts'
    inputs:
      artifactName: 'Cygwin SITL binaries'
      pathtoPublish: 'build/sitl/bin'
#      targetPath: 'build/sitl/bin'

- template: autotest_template.yml
  parameters:
    name: 'Copter'
    build_target: 'ArduCopter'
    action_target: 'ArduCopter'

- template: autotest_template.yml
  parameters:
    name: 'Plane'
    build_target: 'ArduPlane'
    action_target: 'ArduPlane'

- template: autotest_template.yml
  parameters:
    name: 'Quadplane'
    build_target: 'ArduPlane'
    action_target: 'QuadPlane'

- template: autotest_template.yml
  parameters:
    name: 'Rover'
    build_target: 'APMrover2'
    action: 'drive'
    action_target: 'APMrover2'

- template: autotest_template.yml
  parameters:
    name: 'Sub'
    build_target: 'ArduSub'
    action: 'dive'
    action_target: 'ArduSub'

